#!/bin/sh
set -eu

MOTIS_CONFIG="${MOTIS_CONFIG:-/var/lib/motis/config.yml}"

# Wait for config file to be generated by the updater
if [ ! -f "${MOTIS_CONFIG}" ]; then
  echo "Waiting for MOTIS config at ${MOTIS_CONFIG}..."
  while [ ! -f "${MOTIS_CONFIG}" ]; do
    sleep 5
  done
  echo "Config file found."
fi

# Wait for import to complete (marker file created by update_data.ts)
if [ ! -f "/var/lib/motis/.import-complete" ]; then
  echo "Waiting for motis import to complete..."
  while [ ! -f "/var/lib/motis/.import-complete" ]; do
    sleep 5
  done
  echo "Import complete."
fi

cd /var/lib/motis
exec /opt/motis/motis server "$@"
